### ISSUE TITLE
Put motion changes behind config flag

### ISSUE THREAD

**Issue by jeaye** [tpope/vim-sexp-mappings-for-regular-people#10]
>  I've taken over the WORD motions--W, B, E, gE--instead, operating under the theory that those aren't nearly as useful in a language where so many punctuation marks are identifier characters. This might be a terrible idea.

I think it might be, since it's counter to everything that we do in other filetypes with words and boundaries. Since I don't believe I can unmap this in my own config, are you open to putting it behind a config flag (defaulting to whatever you want)?

**Comment by ashnur** [comment]
I am frustrated by this, because it skips long strings with spaces. I understand the logic behind the original idea, otoh, I have other ways to navigate if the word skipping becomes too granular. Without that, I am afraid I don't know how to get at the granularity I am used to.
