### ISSUE TITLE
ds( sometimes messes up the expression completely

### ISSUE THREAD

**Issue by timrobinson33** [tpope/vim-sexp-mappings-for-regular-people#14]
given the following expression (laid out exactly as shown)

```
(str
  1
  (str "foo"
       ))
(str "bar ")
```
put the cursor in the second `str` and type `ds(`

the result is
```
(str "bar ")
str "foo"
```
the problem seems to be related to line breaks because if you join the `))` to the preceding line like this 
```
(str
  1
  (str "foo"))
(str "bar ")
```
it works fine

**Comment by tpope** [comment]
This plugin provides `dsf`. `ds(` sounds like surround.vim. You can open a bug there if you like, but know that I don't really proactively chase down surround.vim bugs these days.
