### ISSUE TITLE
Slurping and barfing changes cursor position

### ISSUE THREAD

**Issue by kindlychung** [tpope/vim-sexp-mappings-for-regular-people#5]
For example:

    (f1 (f2 fC3 f4))

cursor position marked by C. After barfing once to the left, the cursor moves to the left paren:

    (f1 f2 (Cf3 f4))

This is quite annoying compared to paredit in emacs. Is there an option to make the cursor stay where it was? 

Thanks!

**Comment by tpope** [comment]
You should inquire on [vim-sexp](/guns/vim-sexp) proper, as to the best of my knowledge the mappings don't/can't have a say in this matter.
