### ISSUE TITLE
barfage and slurpage not working

### ISSUE THREAD

**Issue by favetelinguis** [tpope/vim-sexp-mappings-for-regular-people#6]
Everything in the plugin is working find except barfage and slurpage.

The behavior I get when useing  any of >) >( <) <) the line get moved left or right and the market moves to the first opening bracket. Any ide what is going on, all the other command works fine. Im been using vim 7.4.410.

**Comment by tpope** [comment]
Try typing faster.

**Comment by favetelinguis** [comment]
No does not help.

**Comment by tpope** [comment]
Check `:verbose nmap >)` to confirm the map is there.

**Comment by favetelinguis** [comment]
Sorry man not sure what was going on, not it seems to be working. Might have some other issues with my vimrc screwing things up. You can close this issue.

BTW Thanks for all the awsome plugins!

**Comment by jcpsantiago** [comment]
I'm experiencing this with the current version of the plugin in Neovim.
`:verbose nmap >)` says `No mapping found`.

I also tried using only 

This is my `~/.config/nvim/init.vim` (mostly commented-out to debug while I debug this issue)
```
 " Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'

" Clojure
" Plug 'tpope/vim-fireplace', 				{'for': 'clojure'}
Plug 'tpope/vim-sexp-mappings-for-regular-people', 	{'for': 'clojure'}
Plug 'guns/vim-sexp',    				{'for': 'clojure'}
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
" Plug 'eraserhd/parinfer-rust'
" Plug 'guns/vim-clojure-static'
" Plug 'guns/vim-clojure-highlight'

" Autocomplete
" Plug 'Shougo/deoplete.nvim'
" Plug 'dense-analysis/ale'
" Plug 'honza/vim-snippets'
" Plug 'sirver/ultisnips'

" UI
" Plug 'itchyny/lightline.vim'
" Plug 'yggdroot/indentline'
" Plug 'yuttie/comfortable-motion.vim'
Plug 'arcticicestudio/nord-vim'
" Plug 'kaicataldo/material.vim'
" Plug 'nlknguyen/papercolor-theme'

" Filesystem
" Plug 'preservim/nerdtree'
" Plug 'junegunn/fzf'

" Version control
" Plug 'airblade/vim-gitgutter'
" Plug 'itchyny/vim-gitbranch' 

" Utils
" Plug 'farmergreg/vim-lastplace'
Plug 'tpope/vim-commentary'
" Plug 'mechatroner/rainbow_csv'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Use deoplete.
" let g:deoplete#enable_at_startup = 1

" Auto-reload file changes
set autoread

set termguicolors
set number
set cursorline
set updatetime=100
set noshowmode

set undodir=~/.vim/undo
set undofile

colorscheme nord

" " set theme for lightline
" let g:lightline = { 
" 	\ 'colorscheme': 'nord',
"       	\ 'active': {
"       	\   'left': [ [ 'mode', 'paste' ],
"       	\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
" 	\ },
" 	\ 'component_function': {
"       	\ 'gitbranch': 'gitbranch#name'
"       	\ }}

" set Ctrl + N to toggle NERDtree
" map <C-n> :NERDTreeToggle<CR>

" " add highlight to 81st character
" highlight ColorColumn ctermbg=magenta
" call matchadd('ColorColumn', '\%81v', 100)

" for code linting
" let g:ale_linters = {'clojure': ['clj-kondo']}
```
Like the OP `>)` increases indentation.

Please let me know how I can help you help me :)

**Comment by jcpsantiago** [comment]
I'm experiencing this with the current version of the plugin in Neovim.
`:verbose nmap >)` says `No mapping found`.

I also tried using only 

This is my `~/.config/nvim/init.vim` (mostly commented-out to debug while I debug this issue)
```
 " Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'

" Clojure
" Plug 'tpope/vim-fireplace', 				{'for': 'clojure'}
Plug 'tpope/vim-sexp-mappings-for-regular-people', 	{'for': 'clojure'}
Plug 'guns/vim-sexp',    				{'for': 'clojure'}
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
" Plug 'eraserhd/parinfer-rust'
" Plug 'guns/vim-clojure-static'
" Plug 'guns/vim-clojure-highlight'

" Autocomplete
" Plug 'Shougo/deoplete.nvim'
" Plug 'dense-analysis/ale'
" Plug 'honza/vim-snippets'
" Plug 'sirver/ultisnips'

" UI
" Plug 'itchyny/lightline.vim'
" Plug 'yggdroot/indentline'
" Plug 'yuttie/comfortable-motion.vim'
Plug 'arcticicestudio/nord-vim'
" Plug 'kaicataldo/material.vim'
" Plug 'nlknguyen/papercolor-theme'

" Filesystem
" Plug 'preservim/nerdtree'
" Plug 'junegunn/fzf'

" Version control
" Plug 'airblade/vim-gitgutter'
" Plug 'itchyny/vim-gitbranch' 

" Utils
" Plug 'farmergreg/vim-lastplace'
Plug 'tpope/vim-commentary'
" Plug 'mechatroner/rainbow_csv'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Use deoplete.
" let g:deoplete#enable_at_startup = 1

" Auto-reload file changes
set autoread

set termguicolors
set number
set cursorline
set updatetime=100
set noshowmode

set undodir=~/.vim/undo
set undofile

colorscheme nord

" " set theme for lightline
" let g:lightline = { 
" 	\ 'colorscheme': 'nord',
"       	\ 'active': {
"       	\   'left': [ [ 'mode', 'paste' ],
"       	\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
" 	\ },
" 	\ 'component_function': {
"       	\ 'gitbranch': 'gitbranch#name'
"       	\ }}

" set Ctrl + N to toggle NERDtree
" map <C-n> :NERDTreeToggle<CR>

" " add highlight to 81st character
" highlight ColorColumn ctermbg=magenta
" call matchadd('ColorColumn', '\%81v', 100)

" for code linting
" let g:ale_linters = {'clojure': ['clj-kondo']}
```
Like the OP `>)` increases indentation.

@tpope  Please let me know how I can help you help me :)

**Comment by roddyyaga** [comment]
> Try typing faster.

This solved my problem, what's the reason something else happens when you wait a while between key presses?

**Comment by tpope** [comment]
`:help 'timeout'`. My vimrc has this:

```vim
setglobal timeoutlen=1200
setglobal ttimeoutlen=50
```

**Comment by roddyyaga** [comment]
Thank you!

**Comment by willocho** [comment]
> I'm experiencing this with the current version of the plugin in Neovim. `:verbose nmap >)` says `No mapping found`.
> 
> I also tried using only
> 
> This is my `~/.config/nvim/init.vim` (mostly commented-out to debug while I debug this issue)
> 
> ```
>  " Plugins will be downloaded under the specified directory.
> call plug#begin('~/.vim/plugged')
> 
> " Declare the list of plugins.
> Plug 'tpope/vim-sensible'
> 
> " Clojure
> " Plug 'tpope/vim-fireplace', 				{'for': 'clojure'}
> Plug 'tpope/vim-sexp-mappings-for-regular-people', 	{'for': 'clojure'}
> Plug 'guns/vim-sexp',    				{'for': 'clojure'}
> Plug 'tpope/vim-repeat'
> Plug 'tpope/vim-surround'
> " Plug 'eraserhd/parinfer-rust'
> " Plug 'guns/vim-clojure-static'
> " Plug 'guns/vim-clojure-highlight'
> 
> " Autocomplete
> " Plug 'Shougo/deoplete.nvim'
> " Plug 'dense-analysis/ale'
> " Plug 'honza/vim-snippets'
> " Plug 'sirver/ultisnips'
> 
> " UI
> " Plug 'itchyny/lightline.vim'
> " Plug 'yggdroot/indentline'
> " Plug 'yuttie/comfortable-motion.vim'
> Plug 'arcticicestudio/nord-vim'
> " Plug 'kaicataldo/material.vim'
> " Plug 'nlknguyen/papercolor-theme'
> 
> " Filesystem
> " Plug 'preservim/nerdtree'
> " Plug 'junegunn/fzf'
> 
> " Version control
> " Plug 'airblade/vim-gitgutter'
> " Plug 'itchyny/vim-gitbranch' 
> 
> " Utils
> " Plug 'farmergreg/vim-lastplace'
> Plug 'tpope/vim-commentary'
> " Plug 'mechatroner/rainbow_csv'
> 
> " List ends here. Plugins become visible to Vim after this call.
> call plug#end()
> 
> " Use deoplete.
> " let g:deoplete#enable_at_startup = 1
> 
> " Auto-reload file changes
> set autoread
> 
> set termguicolors
> set number
> set cursorline
> set updatetime=100
> set noshowmode
> 
> set undodir=~/.vim/undo
> set undofile
> 
> colorscheme nord
> 
> " " set theme for lightline
> " let g:lightline = { 
> " 	\ 'colorscheme': 'nord',
> "       	\ 'active': {
> "       	\   'left': [ [ 'mode', 'paste' ],
> "       	\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
> " 	\ },
> " 	\ 'component_function': {
> "       	\ 'gitbranch': 'gitbranch#name'
> "       	\ }}
> 
> " set Ctrl + N to toggle NERDtree
> " map <C-n> :NERDTreeToggle<CR>
> 
> " " add highlight to 81st character
> " highlight ColorColumn ctermbg=magenta
> " call matchadd('ColorColumn', '\%81v', 100)
> 
> " for code linting
> " let g:ale_linters = {'clojure': ['clj-kondo']}
> ```
> 
> Like the OP `>)` increases indentation.
> 
> [@tpope](https://github.com/tpope) Please let me know how I can help you help me :)

Did you ever figure this out? This is also happening for me in clojure file I'm working on.
