### ISSUE TITLE
Better map for ")"

### ISSUE THREAD

**Issue by MightyPixel** [tpope/vim-sexp-mappings-for-regular-people#7]
Hi,

In the case when you have something like: "(f (a b)" and you want to insert a ')' after the 'a' typing in insert mode ')' takes you to the ')' after the 'b' (because of the "sexp_move_to_next_bracket"). Wouldn't be nice if the sexp_move_to_next_bracket works only in normal mode? Is it okay for this plugin to fix this?

Am I missing something?

Cheers

**Comment by morrifeldman** [comment]
try this in your .vimrc

let g:sexp_enable_insert_mode_mappings = 0

**Comment by tpope** [comment]
Yeah if there is a one line option for it I don't see a point in my plugin forcing the issue. Personally I have just learned to type `<C-V>)` whenever I am doing something "unconventional" (rare for parentheses but sometimes happens for quotes).
