### ISSUE TITLE
Mapping >]

### ISSUE THREAD

**Issue by alcesleo** [tpope/vim-sexp-mappings-for-regular-people#8]
Hi! I frequently run into wanting to use these mappings with square brackets in Clojure - is there any reason why for example `>]` is not mapped? Could I accomplish this in some easy way?

Thanks a lot!

**Comment by tpope** [comment]
`>]` would behave identically to `>)` and would conflict with some more contrived indentation dispatches like `>]z` (indent till next fold). It certainly *could* be accomplished with the right autocommand but I wouldn't recommend it.

**Comment by alcesleo** [comment]
> `>]` would behave identically to `>)`

D'oh. You're right, thank you
